name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t bannACR.azurecr.io/tetris . --file Dockerfile --tag my-image-name:$(date +%s)


       
#   push-image:
#     runs-on: ubuntu-latest
      
#     steps:
#     - uses:
#     - name: 
#       run: withCredentials([usernamePassword(credentialsId: 'acr', passwordVariable: 'password', usernameVariable: 'username')]) {
#                 sh 'docker login -u ${username} -p ${password} bannACR.azurecr.io'
#                 sh 'docker push bannACR.azurecr.io/tetris'
        
#   deploy-web-app:
#     runs-on:
#     steps:
#                 withCredentials([azureServicePrincipal('azure_service_principal')]) {
#                 sh 'az login --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} --tenant ${AZURE_TENANT_ID}'
#                 }
#                 withCredentials([usernamePassword(credentialsId: 'acr', passwordVariable: 'password', usernameVariable: 'username')]) {
#                 sh 'az webapp config container set --name bann-app --resource-group rg1 --docker-custom-image-name bannACR.azurecr.io/tetris:latest --docker-registry-server-url https://bannACR.azurecr.io --docker-registry-server-user ${username} --docker-registry-server-password ${password}'
