name: docker_build_push_acr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
   run:
     shell: bash
     
jobs:

  docker_build_push_acr:
     runs-on: ubuntu-latest
     environment: production
 
     steps:
     # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v3
  
     - name: Azure Login
       uses: azure/docker-login@v1
       with:
         login-server: ${{ secrets.LOGIN_SERVER }}
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}
    
     - name: "Docker Build and Push to ACR"
       uses: azure/docker-login@v1
       with:
         login-server: ${{ secrets.LOGIN_SERVER }}
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}

     - run: |
         docker build . -t bannacr.azurecr.io/tetris:${{ github.sha }}
         docker push bannacr.azurecr.io/tetris:latest
