name: docker_build_push_acr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
   run:
     shell: bash
permissions: 
     id-token: write
     contents: read

jobs:

# 1.Job
  build_and_push_acr:
     runs-on: ubuntu-latest
     environment: production
     needs:
       login-to-Azure
     steps:
     # Checkout the repository to the GitHub Actions runner
     - name: "Checkout Github Action"
       uses: actions/checkout@v3
  
     - name: "Docker Build and Push to ACR"
       uses: azure/docker-login@v1
       with:
         login-server: ${{ secrets.LOGIN_SERVER }}
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}
     - run: |
         docker build . -t ${{ secrets.LOGIN_SERVER }}/tetris:latest
         docker push bannacr.azurecr.io/tetris:latest
 # 2.Job 
  deploy:
     runs-on: ubuntu-latest
     environment: production
     needs:
        build_and_push_acr
        
     steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
      - name: 'Set private registry authentication settings'
        run: az webapp config container set --name bannwebapp --resource-group web-app-rg --docker-registry-server-user ${{ secrets.ACR_USERNAME }} --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
    
      - uses: azure/webapps-deploy@v2
        with:
         app-name: 'bannwebapp'
         images: 'bannacr.azurecr.io/tetris:latest'
